// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8YdQ5b2IHLeNJNfcqiCN8TeZj6cmmefE',
    appId: '1:764122592903:web:1f029df0d9b0e07f60ea22',
    messagingSenderId: '764122592903',
    projectId: 'ssoft-vistoria',
    authDomain: 'ssoft-vistoria.firebaseapp.com',
    databaseURL: 'https://ssoft-vistoria-default-rtdb.firebaseio.com',
    storageBucket: 'ssoft-vistoria.appspot.com',
    measurementId: 'G-E4GP7MKF6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPvpH2oEhTFKOm1FpdBYzubYRYQ_6sqd8',
    appId: '1:764122592903:android:d70dbc13a429cdb160ea22',
    messagingSenderId: '764122592903',
    projectId: 'ssoft-vistoria',
    databaseURL: 'https://ssoft-vistoria-default-rtdb.firebaseio.com',
    storageBucket: 'ssoft-vistoria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0dsJDsrzop1UTcXdpfN2NaA_1i_8ur4',
    appId: '1:764122592903:ios:128611e1483374bc60ea22',
    messagingSenderId: '764122592903',
    projectId: 'ssoft-vistoria',
    databaseURL: 'https://ssoft-vistoria-default-rtdb.firebaseio.com',
    storageBucket: 'ssoft-vistoria.appspot.com',
    iosClientId: '764122592903-0oolo67h49ajenln095nhfv0l51svmi4.apps.googleusercontent.com',
    iosBundleId: 'com.ssoft.ssoftVistoria',
  );
}
